apiVersion: v1
kind: ConfigMap
metadata:
  name: ecom-config
  namespace: ecommerce-lab
data:
  APP_ENV: "production"
  SERVER_PORT: "8080"
  REDIS_URL: "redis://redis-service:6379"
  KAFKA_BROKERS: "redpanda-service:9092"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecom-secrets
  namespace: ecommerce-lab
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres-primary:5432/ecommerce_lab"
  READ_ONLY_DATABASE_URL: "postgres://postgres:postgres@postgres-replica:5435/ecommerce_lab"
  JWT_SECRET: "super-secret-jwt-key-k8s-milestone-v7"
